### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by dragonfire1119** [brandonxiang/vue-leaflet#2]
This doesn't seem to be on the npmjs?

**Comment by brandonxiang** [comment]
It is under construction, so it has not been published on npmjs.

**Comment by dragonfire1119** [comment]
@brandonxiang Ok I just wondered. When do you think it might be released? Thanks for your time.

**Comment by brandonxiang** [comment]
@dragonfire1119 It is ready to install on npmjs `npm install vue_leaflet --save`
